FROM ubuntu:latest
LABEL maintainer="siakhooi@gmail.com"
LABEL name="java-cikit"
LABEL objective="CI Kit for Java projects"
LABEL version="1.2.2"
LABEL description="CI Kit for java projects, using default: ubuntu,default-jdk,ant,maven,junit,junit4,init maven with `maven-archetype-quickstart`"
LABEL org.opencontainers.image.source https://github.com/siakhooi/docker-java-cikit

COPY cikit /usr/bin
RUN chmod 755 /usr/bin/cikit \
  && apt -y update \
  && apt -y install default-jdk ant maven junit junit4 \
  && mvn archetype:generate -DgroupId=xxxxxxxx -DartifactId=yyyyyyyy -DarchetypeArtifactId=maven-archetype-quickstart -DarchetypeVersion=1.4 -DinteractiveMode=false \
  && cd yyyyyyyy && mvn package && cd .. && rm -rf yyyyyyyy
