name: Test on Merge to master

env:
  DOCKERFILE1: Dockerfile_default
  TAG1: java-cikit:default
  FILE1: java-cikit.tar.gz

on:
  push:
    branches: [master]

jobs:
  test_docker_build:
    name: Test Docker Build
    runs-on: ubuntu-latest
    container:
      image: docker:dind
    steps:
      - uses: actions/checkout@v2
      - run: docker build -f $DOCKERFILE1 -t $TAG1 .
      - run: docker images
      - run: docker save $TAG1 | gzip > $FILE1
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.FILE1 }}
          path: ${{ env.FILE1 }}
