name: Push release to GitHub Container Registry

env:
  DOCKERFILE1: Dockerfile_default
  REGISTRY: docker.pkg.github.com
  REGISTRY_USER: siakhooi
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD_GCR }}
  TAG1: siakhooi/docker-java-cikit/java-cikit:default
  TAG2: siakhooi/docker-java-cikit/java-cikit:default-${{ github.event.release.tag_name }}
  FILE1: java-cikit.tar.gz

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    container:
      image: docker:dind
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u $REGISTRY_USER -p "$REGISTRY_PASSWORD" $REGISTRY
      - run: docker build -f $DOCKERFILE1 -t $REGISTRY/$TAG1 -t $REGISTRY/$TAG2  .
      - run: docker images
      - run: docker push $REGISTRY/$TAG1
      - run: docker push $REGISTRY/$TAG2
      - run: docker save $REGISTRY/$TAG1 | gzip > $FILE1
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.FILE1 }}
          path: ${{ env.FILE1 }}
